#! /bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width         4
bspc config window_gap           8
bspc config split_ratio          0.50
# bspc config top_padding          20
# bspc config bottom_padding       30

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer false

bspc config normal_border_color  "#222222"
bspc config focused_border_color "#CB163F"
bspc config active_border_color  "#1d1d1d"

# Setup our mouse pointer
xsetroot -cursor_name left_ptr

# Make sure our refresh rate is set to 144
xrandr --output DP-0 --mode 1920x1080 --rate 144.00

# Workspace 1
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a discord desktop='^1' follow=on focus=on

# Workspace 2
bspc rule -a VSCodium desktop='^2' follow=on focus=on

# Kill if already running
killall -q sxhkd polybar picom dunst

# Launch polybar
polybar -r cawk &

# Paint our background with feh
feh --bg-fill ~/.config/bspwm/backgrounds/1.png &

# Launch dunst notification daemon
dunst &

# Launch sxhkd keybind daemon
sxhkd &

# Launch our standalone compositor
picom &

# Launch us a terminal to get started
alacritty
